// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

package message

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type TARGET int32

const (
	TARGET_USERS    TARGET = 1
	TARGET_COLUMNS  TARGET = 2
	TARGET_PROJECTS TARGET = 3
	TARGET_CARDS    TARGET = 4
	TARGET_ADMIN    TARGET = 5
	TARGET_IDENT    TARGET = 6
	TARGET_NOTIF    TARGET = 7
	TARGET_METADATA TARGET = 8
)

var TARGET_name = map[int32]string{
	1: "USERS",
	2: "COLUMNS",
	3: "PROJECTS",
	4: "CARDS",
	5: "ADMIN",
	6: "IDENT",
	7: "NOTIF",
	8: "METADATA",
}
var TARGET_value = map[string]int32{
	"USERS":    1,
	"COLUMNS":  2,
	"PROJECTS": 3,
	"CARDS":    4,
	"ADMIN":    5,
	"IDENT":    6,
	"NOTIF":    7,
	"METADATA": 8,
}

func (x TARGET) Enum() *TARGET {
	p := new(TARGET)
	*p = x
	return p
}
func (x TARGET) String() string {
	return proto.EnumName(TARGET_name, int32(x))
}
func (x TARGET) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *TARGET) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TARGET_value, data, "TARGET")
	if err != nil {
		return err
	}
	*x = TARGET(value)
	return nil
}

type CMD int32

const (
	CMD_CREATE     CMD = 1
	CMD_MODIFY     CMD = 2
	CMD_DELETE     CMD = 3
	CMD_GET        CMD = 4
	CMD_MOVE       CMD = 5
	CMD_CONNECT    CMD = 6
	CMD_DISCONNECT CMD = 7
	CMD_ERROR      CMD = 8
	CMD_SUCCES     CMD = 9
	CMD_NONE       CMD = 10
	CMD_PASSWORD   CMD = 11
)

var CMD_name = map[int32]string{
	1:  "CREATE",
	2:  "MODIFY",
	3:  "DELETE",
	4:  "GET",
	5:  "MOVE",
	6:  "CONNECT",
	7:  "DISCONNECT",
	8:  "ERROR",
	9:  "SUCCES",
	10: "NONE",
	11: "PASSWORD",
}
var CMD_value = map[string]int32{
	"CREATE":     1,
	"MODIFY":     2,
	"DELETE":     3,
	"GET":        4,
	"MOVE":       5,
	"CONNECT":    6,
	"DISCONNECT": 7,
	"ERROR":      8,
	"SUCCES":     9,
	"NONE":       10,
	"PASSWORD":   11,
}

func (x CMD) Enum() *CMD {
	p := new(CMD)
	*p = x
	return p
}
func (x CMD) String() string {
	return proto.EnumName(CMD_name, int32(x))
}
func (x CMD) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *CMD) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CMD_value, data, "CMD")
	if err != nil {
		return err
	}
	*x = CMD(value)
	return nil
}

type Msg struct {
	Target           *TARGET       `protobuf:"varint,1,req,name=target,enum=message.TARGET" json:"target,omitempty"`
	Command          *CMD          `protobuf:"varint,2,req,name=command,enum=message.CMD" json:"command,omitempty"`
	AuthorId         *uint32       `protobuf:"varint,3,req,name=author_id" json:"author_id,omitempty"`
	SessionId        *string       `protobuf:"bytes,4,req,name=session_id" json:"session_id,omitempty"`
	Users            *Msg_Users    `protobuf:"bytes,5,opt,name=users" json:"users,omitempty"`
	Columns          *Msg_Columns  `protobuf:"bytes,6,opt,name=columns" json:"columns,omitempty"`
	Projects         *Msg_Projects `protobuf:"bytes,7,opt,name=projects" json:"projects,omitempty"`
	Cards            *Msg_Cards    `protobuf:"bytes,8,opt,name=cards" json:"cards,omitempty"`
	Ident            *Msg_Ident    `protobuf:"bytes,9,opt,name=ident" json:"ident,omitempty"`
	Error            *Msg_Error    `protobuf:"bytes,10,opt,name=error" json:"error,omitempty"`
	Notif            *Msg_Notif    `protobuf:"bytes,11,opt,name=notif" json:"notif,omitempty"`
	Password         *Msg_Password `protobuf:"bytes,12,opt,name=password" json:"password,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (this *Msg) Reset()         { *this = Msg{} }
func (this *Msg) String() string { return proto.CompactTextString(this) }
func (*Msg) ProtoMessage()       {}

func (this *Msg) GetTarget() TARGET {
	if this != nil && this.Target != nil {
		return *this.Target
	}
	return 0
}

func (this *Msg) GetCommand() CMD {
	if this != nil && this.Command != nil {
		return *this.Command
	}
	return 0
}

func (this *Msg) GetAuthorId() uint32 {
	if this != nil && this.AuthorId != nil {
		return *this.AuthorId
	}
	return 0
}

func (this *Msg) GetSessionId() string {
	if this != nil && this.SessionId != nil {
		return *this.SessionId
	}
	return ""
}

func (this *Msg) GetUsers() *Msg_Users {
	if this != nil {
		return this.Users
	}
	return nil
}

func (this *Msg) GetColumns() *Msg_Columns {
	if this != nil {
		return this.Columns
	}
	return nil
}

func (this *Msg) GetProjects() *Msg_Projects {
	if this != nil {
		return this.Projects
	}
	return nil
}

func (this *Msg) GetCards() *Msg_Cards {
	if this != nil {
		return this.Cards
	}
	return nil
}

func (this *Msg) GetIdent() *Msg_Ident {
	if this != nil {
		return this.Ident
	}
	return nil
}

func (this *Msg) GetError() *Msg_Error {
	if this != nil {
		return this.Error
	}
	return nil
}

func (this *Msg) GetNotif() *Msg_Notif {
	if this != nil {
		return this.Notif
	}
	return nil
}

func (this *Msg) GetPassword() *Msg_Password {
	if this != nil {
		return this.Password
	}
	return nil
}

type Msg_Users struct {
	Id               *uint32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Password         *string `protobuf:"bytes,3,req,name=password" json:"password,omitempty"`
	Admin            *bool   `protobuf:"varint,4,req,name=admin" json:"admin,omitempty"`
	Mail             *string `protobuf:"bytes,5,opt,name=mail" json:"mail,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *Msg_Users) Reset()         { *this = Msg_Users{} }
func (this *Msg_Users) String() string { return proto.CompactTextString(this) }
func (*Msg_Users) ProtoMessage()       {}

func (this *Msg_Users) GetId() uint32 {
	if this != nil && this.Id != nil {
		return *this.Id
	}
	return 0
}

func (this *Msg_Users) GetName() string {
	if this != nil && this.Name != nil {
		return *this.Name
	}
	return ""
}

func (this *Msg_Users) GetPassword() string {
	if this != nil && this.Password != nil {
		return *this.Password
	}
	return ""
}

func (this *Msg_Users) GetAdmin() bool {
	if this != nil && this.Admin != nil {
		return *this.Admin
	}
	return false
}

func (this *Msg_Users) GetMail() string {
	if this != nil && this.Mail != nil {
		return *this.Mail
	}
	return ""
}

type Msg_Password struct {
	Id               *uint32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Oldpassword      *string `protobuf:"bytes,2,req,name=oldpassword" json:"oldpassword,omitempty"`
	Newpassword      *string `protobuf:"bytes,3,req,name=newpassword" json:"newpassword,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *Msg_Password) Reset()         { *this = Msg_Password{} }
func (this *Msg_Password) String() string { return proto.CompactTextString(this) }
func (*Msg_Password) ProtoMessage()       {}

func (this *Msg_Password) GetId() uint32 {
	if this != nil && this.Id != nil {
		return *this.Id
	}
	return 0
}

func (this *Msg_Password) GetOldpassword() string {
	if this != nil && this.Oldpassword != nil {
		return *this.Oldpassword
	}
	return ""
}

func (this *Msg_Password) GetNewpassword() string {
	if this != nil && this.Newpassword != nil {
		return *this.Newpassword
	}
	return ""
}

type Msg_Columns struct {
	ProjectId        *uint32  `protobuf:"varint,1,req,name=project_id" json:"project_id,omitempty"`
	Id               *uint32  `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	Name             *string  `protobuf:"bytes,3,req,name=name" json:"name,omitempty"`
	Desc             *string  `protobuf:"bytes,4,opt,name=desc" json:"desc,omitempty"`
	Tags             []string `protobuf:"bytes,5,rep,name=tags" json:"tags,omitempty"`
	ScriptsIds       []uint32 `protobuf:"varint,6,rep,name=scripts_ids" json:"scripts_ids,omitempty"`
	Write            []uint32 `protobuf:"varint,7,rep,name=write" json:"write,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (this *Msg_Columns) Reset()         { *this = Msg_Columns{} }
func (this *Msg_Columns) String() string { return proto.CompactTextString(this) }
func (*Msg_Columns) ProtoMessage()       {}

func (this *Msg_Columns) GetProjectId() uint32 {
	if this != nil && this.ProjectId != nil {
		return *this.ProjectId
	}
	return 0
}

func (this *Msg_Columns) GetId() uint32 {
	if this != nil && this.Id != nil {
		return *this.Id
	}
	return 0
}

func (this *Msg_Columns) GetName() string {
	if this != nil && this.Name != nil {
		return *this.Name
	}
	return ""
}

func (this *Msg_Columns) GetDesc() string {
	if this != nil && this.Desc != nil {
		return *this.Desc
	}
	return ""
}

type Msg_Projects struct {
	Id               *uint32  `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Name             *string  `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	AdminsId         []uint32 `protobuf:"varint,3,rep,name=admins_id" json:"admins_id,omitempty"`
	Read             []uint32 `protobuf:"varint,4,rep,name=read" json:"read,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (this *Msg_Projects) Reset()         { *this = Msg_Projects{} }
func (this *Msg_Projects) String() string { return proto.CompactTextString(this) }
func (*Msg_Projects) ProtoMessage()       {}

func (this *Msg_Projects) GetId() uint32 {
	if this != nil && this.Id != nil {
		return *this.Id
	}
	return 0
}

func (this *Msg_Projects) GetName() string {
	if this != nil && this.Name != nil {
		return *this.Name
	}
	return ""
}

type Msg_Cards struct {
	Id               *uint32  `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	ProjectId        *uint32  `protobuf:"varint,2,req,name=project_id" json:"project_id,omitempty"`
	ColumnId         *uint32  `protobuf:"varint,3,req,name=column_id" json:"column_id,omitempty"`
	Name             *string  `protobuf:"bytes,4,req,name=name" json:"name,omitempty"`
	Desc             *string  `protobuf:"bytes,6,opt,name=desc" json:"desc,omitempty"`
	Tags             []string `protobuf:"bytes,7,rep,name=tags" json:"tags,omitempty"`
	UserId           *uint32  `protobuf:"varint,8,opt,name=user_id" json:"user_id,omitempty"`
	ScriptsIds       []uint32 `protobuf:"varint,9,rep,name=scripts_ids" json:"scripts_ids,omitempty"`
	Write            []uint32 `protobuf:"varint,10,rep,name=write" json:"write,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (this *Msg_Cards) Reset()         { *this = Msg_Cards{} }
func (this *Msg_Cards) String() string { return proto.CompactTextString(this) }
func (*Msg_Cards) ProtoMessage()       {}

func (this *Msg_Cards) GetId() uint32 {
	if this != nil && this.Id != nil {
		return *this.Id
	}
	return 0
}

func (this *Msg_Cards) GetProjectId() uint32 {
	if this != nil && this.ProjectId != nil {
		return *this.ProjectId
	}
	return 0
}

func (this *Msg_Cards) GetColumnId() uint32 {
	if this != nil && this.ColumnId != nil {
		return *this.ColumnId
	}
	return 0
}

func (this *Msg_Cards) GetName() string {
	if this != nil && this.Name != nil {
		return *this.Name
	}
	return ""
}

func (this *Msg_Cards) GetDesc() string {
	if this != nil && this.Desc != nil {
		return *this.Desc
	}
	return ""
}

func (this *Msg_Cards) GetUserId() uint32 {
	if this != nil && this.UserId != nil {
		return *this.UserId
	}
	return 0
}

type Msg_Comment struct {
	Id               *uint32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Content          *string `protobuf:"bytes,2,req,name=content" json:"content,omitempty"`
	AuthorId         *string `protobuf:"bytes,3,req,name=author_id" json:"author_id,omitempty"`
	Timestamp        *uint32 `protobuf:"varint,4,req,name=timestamp" json:"timestamp,omitempty"`
	CardId           *uint32 `protobuf:"varint,5,req,name=card_id" json:"card_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *Msg_Comment) Reset()         { *this = Msg_Comment{} }
func (this *Msg_Comment) String() string { return proto.CompactTextString(this) }
func (*Msg_Comment) ProtoMessage()       {}

func (this *Msg_Comment) GetId() uint32 {
	if this != nil && this.Id != nil {
		return *this.Id
	}
	return 0
}

func (this *Msg_Comment) GetContent() string {
	if this != nil && this.Content != nil {
		return *this.Content
	}
	return ""
}

func (this *Msg_Comment) GetAuthorId() string {
	if this != nil && this.AuthorId != nil {
		return *this.AuthorId
	}
	return ""
}

func (this *Msg_Comment) GetTimestamp() uint32 {
	if this != nil && this.Timestamp != nil {
		return *this.Timestamp
	}
	return 0
}

func (this *Msg_Comment) GetCardId() uint32 {
	if this != nil && this.CardId != nil {
		return *this.CardId
	}
	return 0
}

type Msg_Metadata struct {
	ObjectType       *uint32 `protobuf:"varint,1,req,name=object_type" json:"object_type,omitempty"`
	ObjectId         *uint32 `protobuf:"varint,2,req,name=object_id" json:"object_id,omitempty"`
	DataKey          *string `protobuf:"bytes,3,opt,name=data_key" json:"data_key,omitempty"`
	DataValue        *string `protobuf:"bytes,4,opt,name=data_value" json:"data_value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *Msg_Metadata) Reset()         { *this = Msg_Metadata{} }
func (this *Msg_Metadata) String() string { return proto.CompactTextString(this) }
func (*Msg_Metadata) ProtoMessage()       {}

func (this *Msg_Metadata) GetObjectType() uint32 {
	if this != nil && this.ObjectType != nil {
		return *this.ObjectType
	}
	return 0
}

func (this *Msg_Metadata) GetObjectId() uint32 {
    if this != nil && this.ObjectId != nil {
		return *this.ObjectId
	}
	return 0
}

func (this *Msg_Metadata) GetDataKey() string {
	if this != nil && this.DataKey != nil {
		return *this.DataKey
	}
	return ""
}

func (this *Msg_Metadata) GetDataValue() uint32 {
	if this != nil && this.DataValue != nil {
		return *this.DataValue
	}
	return 0
}

type Msg_Ident struct {
	Login            *string `protobuf:"bytes,1,req,name=login" json:"login,omitempty"`
	Password         *string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *Msg_Ident) Reset()         { *this = Msg_Ident{} }
func (this *Msg_Ident) String() string { return proto.CompactTextString(this) }
func (*Msg_Ident) ProtoMessage()       {}

func (this *Msg_Ident) GetLogin() string {
	if this != nil && this.Login != nil {
		return *this.Login
	}
	return ""
}

func (this *Msg_Ident) GetPassword() string {
	if this != nil && this.Password != nil {
		return *this.Password
	}
	return ""
}

type Msg_Error struct {
	ErrorId          *uint32 `protobuf:"varint,1,req,name=error_id" json:"error_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *Msg_Error) Reset()         { *this = Msg_Error{} }
func (this *Msg_Error) String() string { return proto.CompactTextString(this) }
func (*Msg_Error) ProtoMessage()       {}

func (this *Msg_Error) GetErrorId() uint32 {
	if this != nil && this.ErrorId != nil {
		return *this.ErrorId
	}
	return 0
}

type Msg_Notif struct {
	Msg              *string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *Msg_Notif) Reset()         { *this = Msg_Notif{} }
func (this *Msg_Notif) String() string { return proto.CompactTextString(this) }
func (*Msg_Notif) ProtoMessage()       {}

func (this *Msg_Notif) GetMsg() string {
	if this != nil && this.Msg != nil {
		return *this.Msg
	}
	return ""
}

func init() {
	proto.RegisterEnum("message.TARGET", TARGET_name, TARGET_value)
	proto.RegisterEnum("message.CMD", CMD_name, CMD_value)
}
