// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

package message

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type CMD int32

const (
	CMD_X CMD = 1
	CMD_Y CMD = 2
)

var CMD_name = map[int32]string{
	1: "X",
	2: "Y",
}
var CMD_value = map[string]int32{
	"X": 1,
	"Y": 2,
}

func (x CMD) Enum() *CMD {
	p := new(CMD)
	*p = x
	return p
}
func (x CMD) String() string {
	return proto.EnumName(CMD_name, int32(x))
}
func (x CMD) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *CMD) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CMD_value, data, "CMD")
	if err != nil {
		return err
	}
	*x = CMD(value)
	return nil
}

type CIBLE int32

const (
	CIBLE_USERS    CIBLE = 1
	CIBLE_COLUMNS  CIBLE = 2
	CIBLE_PROJECTS CIBLE = 3
	CIBLE_CARDS    CIBLE = 4
	CIBLE_ADMIN    CIBLE = 5
)

var CIBLE_name = map[int32]string{
	1: "USERS",
	2: "COLUMNS",
	3: "PROJECTS",
	4: "CARDS",
	5: "ADMIN",
}
var CIBLE_value = map[string]int32{
	"USERS":    1,
	"COLUMNS":  2,
	"PROJECTS": 3,
	"CARDS":    4,
	"ADMIN":    5,
}

func (x CIBLE) Enum() *CIBLE {
	p := new(CIBLE)
	*p = x
	return p
}
func (x CIBLE) String() string {
	return proto.EnumName(CIBLE_name, int32(x))
}
func (x CIBLE) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *CIBLE) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CIBLE_value, data, "CIBLE")
	if err != nil {
		return err
	}
	*x = CIBLE(value)
	return nil
}

type Msg struct {
	Cible            *CIBLE        `protobuf:"varint,1,req,name=cible,enum=message.CIBLE" json:"cible,omitempty"`
	Users            *Msg_Users    `protobuf:"bytes,2,opt,name=users" json:"users,omitempty"`
	Columns          *Msg_Columns  `protobuf:"bytes,3,opt,name=columns" json:"columns,omitempty"`
	Projects         *Msg_Projects `protobuf:"bytes,4,opt,name=projects" json:"projects,omitempty"`
	Cards            *Msg_Cards    `protobuf:"bytes,5,opt,name=cards" json:"cards,omitempty"`
	Admin            *Msg_Admin    `protobuf:"bytes,6,opt,name=admin" json:"admin,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (this *Msg) Reset()         { *this = Msg{} }
func (this *Msg) String() string { return proto.CompactTextString(this) }
func (*Msg) ProtoMessage()       {}

func (this *Msg) GetCible() CIBLE {
	if this != nil && this.Cible != nil {
		return *this.Cible
	}
	return 0
}

func (this *Msg) GetUsers() *Msg_Users {
	if this != nil {
		return this.Users
	}
	return nil
}

func (this *Msg) GetColumns() *Msg_Columns {
	if this != nil {
		return this.Columns
	}
	return nil
}

func (this *Msg) GetProjects() *Msg_Projects {
	if this != nil {
		return this.Projects
	}
	return nil
}

func (this *Msg) GetCards() *Msg_Cards {
	if this != nil {
		return this.Cards
	}
	return nil
}

func (this *Msg) GetAdmin() *Msg_Admin {
	if this != nil {
		return this.Admin
	}
	return nil
}

type Msg_Users struct {
	Cmd              *CMD   `protobuf:"varint,1,req,name=cmd,enum=message.CMD" json:"cmd,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *Msg_Users) Reset()         { *this = Msg_Users{} }
func (this *Msg_Users) String() string { return proto.CompactTextString(this) }
func (*Msg_Users) ProtoMessage()       {}

func (this *Msg_Users) GetCmd() CMD {
	if this != nil && this.Cmd != nil {
		return *this.Cmd
	}
	return 0
}

type Msg_Columns struct {
	Cmd              *CMD   `protobuf:"varint,1,req,name=cmd,enum=message.CMD" json:"cmd,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *Msg_Columns) Reset()         { *this = Msg_Columns{} }
func (this *Msg_Columns) String() string { return proto.CompactTextString(this) }
func (*Msg_Columns) ProtoMessage()       {}

func (this *Msg_Columns) GetCmd() CMD {
	if this != nil && this.Cmd != nil {
		return *this.Cmd
	}
	return 0
}

type Msg_Projects struct {
	Cmd              *CMD   `protobuf:"varint,1,req,name=cmd,enum=message.CMD" json:"cmd,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *Msg_Projects) Reset()         { *this = Msg_Projects{} }
func (this *Msg_Projects) String() string { return proto.CompactTextString(this) }
func (*Msg_Projects) ProtoMessage()       {}

func (this *Msg_Projects) GetCmd() CMD {
	if this != nil && this.Cmd != nil {
		return *this.Cmd
	}
	return 0
}

type Msg_Cards struct {
	Cmd              *CMD   `protobuf:"varint,1,req,name=cmd,enum=message.CMD" json:"cmd,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *Msg_Cards) Reset()         { *this = Msg_Cards{} }
func (this *Msg_Cards) String() string { return proto.CompactTextString(this) }
func (*Msg_Cards) ProtoMessage()       {}

func (this *Msg_Cards) GetCmd() CMD {
	if this != nil && this.Cmd != nil {
		return *this.Cmd
	}
	return 0
}

type Msg_Admin struct {
	Cmd              *CMD   `protobuf:"varint,1,req,name=cmd,enum=message.CMD" json:"cmd,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *Msg_Admin) Reset()         { *this = Msg_Admin{} }
func (this *Msg_Admin) String() string { return proto.CompactTextString(this) }
func (*Msg_Admin) ProtoMessage()       {}

func (this *Msg_Admin) GetCmd() CMD {
	if this != nil && this.Cmd != nil {
		return *this.Cmd
	}
	return 0
}

func init() {
	proto.RegisterEnum("message.CMD", CMD_name, CMD_value)
	proto.RegisterEnum("message.CIBLE", CIBLE_name, CIBLE_value)
}
